--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8
-- Dumped by pg_dump version 16.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: f_reservation_inserted(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.f_reservation_inserted() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
declare
	v_clashing_reservation_count integer;
begin
	-- check start time and end time
	-- if the timespan clashes with an existing reservation dont continue
	-- if the new start or end time are in the span of some reservation dont continue
	select count(*) into v_clashing_reservation_count 
	from reservation r
	where r.start_time <= NEW.start_time and NEW.start_time <= r.end_time 
	   or r.start_time <= NEW.end_time and NEW.end_time <= r.end_time;

	if v_clashing_reservation_count <> 0 then
		rollback;
	end if;

	-- insert workspace histories  at the start_time and end_time
	insert into workspace_history(workspace_id, status_id, reservation_id, change_at)
	values (NEW.workspace_id, 
			(select workspace_status_id from workspace_status where "name" = 'Occupied'),
			NEW.reservation_id,
			NEW.start_time);

	insert into workspace_history(workspace_id, status_id, reservation_id, change_at)
	values (NEW.workspace_id, 
			(select workspace_status_id from workspace_status where "name" = 'Available'),
			NEW.reservation_id,
			NEW.end_time);

	commit;
end;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Name: address; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.address (
    address_id integer NOT NULL,
    street_address character varying(100) NOT NULL,
    district character varying(50),
    city_id integer NOT NULL,
    postal_code character varying(10) NOT NULL,
    last_updated timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL,
    CONSTRAINT address_latitude_range_constraint CHECK (((latitude >= ('-90'::integer)::numeric) AND (latitude <= (90)::numeric))),
    CONSTRAINT address_longitude_range_constraint CHECK (((longitude >= ('-180'::integer)::numeric) AND (longitude <= (180)::numeric)))
);


--
-- Name: address_address_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.address ALTER COLUMN address_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: city; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.city (
    city_id integer NOT NULL,
    name character varying(50) NOT NULL,
    country_id integer NOT NULL,
    last_updated timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: city_city_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.city ALTER COLUMN city_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.city_city_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: country; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.country (
    country_id integer NOT NULL,
    name character varying(50) NOT NULL,
    last_updated timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: country_country_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.country ALTER COLUMN country_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.country_country_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: coworking_center; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.coworking_center (
    coworking_center_id integer NOT NULL,
    name character varying(256) NOT NULL,
    description character varying NOT NULL,
    last_updated timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    address_id integer NOT NULL,
    updated_by integer
);


--
-- Name: coworking_center_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.coworking_center ALTER COLUMN coworking_center_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coworking_center_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservation (
    reservation_id integer NOT NULL,
    workspace_id integer NOT NULL,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone NOT NULL,
    total_price money,
    pricing_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    customer_id integer,
    is_cancelled boolean DEFAULT false NOT NULL
);


--
-- Name: reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservation ALTER COLUMN reservation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    user_id integer NOT NULL,
    email character varying(256) NOT NULL,
    password_hash character varying NOT NULL,
    role_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    refresh_token character varying(512),
    refresh_token_expiry timestamp without time zone
);


--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."user" ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_role (
    user_role_id integer NOT NULL,
    name character varying(256) NOT NULL,
    description character varying(1024)
);


--
-- Name: user_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_role ALTER COLUMN user_role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspace; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspace (
    workspace_id integer NOT NULL,
    name character varying NOT NULL,
    description character varying NOT NULL,
    coworking_center_id integer NOT NULL,
    is_removed boolean DEFAULT false NOT NULL,
    last_updated timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by integer
);


--
-- Name: workspace_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspace_history (
    workspace_history_id integer NOT NULL,
    workspace_id integer NOT NULL,
    status_id integer NOT NULL,
    change_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    reservation_id integer
);


--
-- Name: workspace_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workspace_history ALTER COLUMN workspace_history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspace_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspace_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workspace ALTER COLUMN workspace_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspace_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspace_pricing; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspace_pricing (
    workspace_pricing_id integer NOT NULL,
    workspace_id integer NOT NULL,
    price_per_hour money NOT NULL,
    valid_from timestamp without time zone NOT NULL,
    valid_until timestamp without time zone,
    created_by integer
);


--
-- Name: COLUMN workspace_pricing.price_per_hour; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.workspace_pricing.price_per_hour IS 'dollar
';


--
-- Name: COLUMN workspace_pricing.created_by; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.workspace_pricing.created_by IS 'if null then it was created by the database admin who has direct access to the database';


--
-- Name: workspace_pricing_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workspace_pricing ALTER COLUMN workspace_pricing_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspace_pricing_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspace_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspace_status (
    workspace_status_id integer NOT NULL,
    name character varying(128) NOT NULL,
    description character varying NOT NULL
);


--
-- Name: workspace_status_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workspace_status ALTER COLUMN workspace_status_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspace_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: address address_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_pkey PRIMARY KEY (address_id);


--
-- Name: city city_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.city
    ADD CONSTRAINT city_pkey PRIMARY KEY (city_id);


--
-- Name: country country_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT country_pkey PRIMARY KEY (country_id);


--
-- Name: coworking_center coworking_center_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coworking_center
    ADD CONSTRAINT coworking_center_pkey PRIMARY KEY (coworking_center_id);


--
-- Name: reservation reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_pkey PRIMARY KEY (reservation_id);


--
-- Name: country unique_country_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT unique_country_name UNIQUE (name);


--
-- Name: user user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_email_key UNIQUE (email);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (user_id);


--
-- Name: user_role user_role_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_role_name_key UNIQUE (name);


--
-- Name: user_role user_role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_role_pkey PRIMARY KEY (user_role_id);


--
-- Name: workspace_history workspace_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_history
    ADD CONSTRAINT workspace_history_pkey PRIMARY KEY (workspace_history_id);


--
-- Name: workspace workspace_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace
    ADD CONSTRAINT workspace_pkey PRIMARY KEY (workspace_id);


--
-- Name: workspace_pricing workspace_pricing_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_pricing
    ADD CONSTRAINT workspace_pricing_pkey PRIMARY KEY (workspace_pricing_id);


--
-- Name: workspace_status workspace_status_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_status
    ADD CONSTRAINT workspace_status_name_key UNIQUE (name);


--
-- Name: workspace_status workspace_status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_status
    ADD CONSTRAINT workspace_status_pkey PRIMARY KEY (workspace_status_id);


--
-- Name: reservation t_reservation_after_inserted; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER t_reservation_after_inserted AFTER INSERT ON public.reservation FOR EACH ROW EXECUTE FUNCTION public.f_reservation_inserted();


--
-- Name: address address_city_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.city(city_id);


--
-- Name: city city_country_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.city
    ADD CONSTRAINT city_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.country(country_id);


--
-- Name: coworking_center coworking_center_address_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coworking_center
    ADD CONSTRAINT coworking_center_address_id_fkey FOREIGN KEY (address_id) REFERENCES public.address(address_id);


--
-- Name: coworking_center coworking_center_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coworking_center
    ADD CONSTRAINT coworking_center_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public."user"(user_id);


--
-- Name: reservation reservation_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public."user"(user_id);


--
-- Name: reservation reservation_pricing_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_pricing_id_fkey FOREIGN KEY (pricing_id) REFERENCES public.workspace_pricing(workspace_pricing_id);


--
-- Name: reservation reservation_workspace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspace(workspace_id);


--
-- Name: user user_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.user_role(user_role_id);


--
-- Name: workspace workspace_coworking_center_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace
    ADD CONSTRAINT workspace_coworking_center_id_fkey FOREIGN KEY (coworking_center_id) REFERENCES public.coworking_center(coworking_center_id);


--
-- Name: workspace_history workspace_history_reservation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_history
    ADD CONSTRAINT workspace_history_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES public.reservation(reservation_id);


--
-- Name: workspace_history workspace_history_status_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_history
    ADD CONSTRAINT workspace_history_status_id_fkey FOREIGN KEY (status_id) REFERENCES public.workspace_status(workspace_status_id);


--
-- Name: workspace_history workspace_history_workspace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_history
    ADD CONSTRAINT workspace_history_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspace(workspace_id);


--
-- Name: workspace_pricing workspace_pricing_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_pricing
    ADD CONSTRAINT workspace_pricing_created_by_fkey FOREIGN KEY (created_by) REFERENCES public."user"(user_id);


--
-- Name: workspace_pricing workspace_pricing_workspace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_pricing
    ADD CONSTRAINT workspace_pricing_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspace(workspace_id);


--
-- Name: workspace workspace_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace
    ADD CONSTRAINT workspace_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public."user"(user_id);


--
-- PostgreSQL database dump complete
--
